// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynkkyixtgikiagnzeknx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlua2t5aXh0Z2lraWFnbnpla254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMjEwNTEsImV4cCI6MjA3Mzc5NzA1MX0.0_xRU3sRYkjNSeNy1QstgLQgd1wrU5boCb5M5Sf6hkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});